### ISSUE TITLE
求加入dm转换为ass或xml弹幕功能

### ISSUE THREAD

**Issue by YanChiCu** [mzky/m4s-converter#1]
请求一起转换连同缓存的弹幕文件释放在文件夹中

**Comment by mzky** [comment]
刚试了一下单个视频可以获取到xml的弹幕，但是我这工具会将合集的各单个视频合成为一个文件，每个视频的xml用在合成的文件可能就用不了,我研究研究。
`https://api.bilibili.com/x/v1/dm/list.so?oid=1415572493`

**Comment by mzky** [comment]
> 请求一起转换连同缓存的弹幕文件释放在文件夹中
可以啦，见新版：https://github.com/mzky/m4s-converter/releases/tag/v1.2.2
![image](https://github.com/mzky/m4s-converter/assets/13345233/6a74deee-e918-415e-b165-a0573a138099)
![image](https://github.com/mzky/m4s-converter/assets/13345233/14da7c55-557f-4483-a0b9-3fec7af4d787)
用法：
![image](https://github.com/mzky/m4s-converter/assets/13345233/ab96d143-0262-46eb-8740-ffa655a41c52)
