### ISSUE TITLE
Mac 不知道如何执行文件 T^T

### ISSUE THREAD

**Issue by karanotsingyu** [mzky/m4s-converter#10]
Arm 64 版本

**Comment by mzky** [comment]
我这没有环境，你可以下载这个版本 控制台执行这行试试 ./m4s-converter-darwin_arm64 
![image](https://github.com/user-attachments/assets/07af4566-eed9-48f2-b82b-d2be2f279561)

**Comment by sherlock-png** [comment]
给了权限，运行时还是提示zsh:killed，不知道什么问题

**Comment by mzky** [comment]
> 给了权限，运行时还是提示zsh:killed，不知道什么问题

我这没有环境，百度了一下，试试行不行：https://blog.csdn.net/m0_46958731/article/details/138999711
![image](https://github.com/user-attachments/assets/15a6b65b-fef5-4958-ad7e-b42ce1be0428)

**Comment by mzky** [comment]
@sherlock-png 搭了一个macos的虚拟机，在上面编译了一版试试还提示么
https://github.com/mzky/m4s-converter/releases/tag/test
