### ISSUE TITLE
部分视频合成后音画不同步

### ISSUE THREAD

**Issue by datou1996** [mzky/m4s-converter#11]
比如：
https://www.bilibili.com/video/BV1vL41127it/?p=2
https://www.bilibili.com/video/BV12Z4y1B7Gs/
缓存后在哔哩哔哩PC端内部播放器播放正常，又尝试使用其它下载器下载均出现相同问题，经过排查发现貌似是缓存转换后视频音频的长度不一致导致的，可能是b站上传转码过程中出现的问题。
合成后就会音画不同步，在pr中按照音频、视频轨结尾对齐音画就同步了，可否修复这个问题或加一个按音视频结尾对齐的参数。

**Comment by mzky** [comment]
> 比如： https://www.bilibili.com/video/BV1vL41127it/?p=2 https://www.bilibili.com/video/BV12Z4y1B7Gs/ 缓存后在哔哩哔哩PC端内部播放器播放正常，又尝试使用其它下载器下载均出现相同问题，经过排查发现貌似是缓存转换后视频音频的长度不一致导致的，可能是b站上传转码过程中出现的问题。 合成后就会音画不同步，在pr中按照音频、视频轨结尾对齐音画就同步了，可否修复这个问题或加一个按音视频结尾对齐的参数。

在视频组里所有音视频都不同步还是某一个不同步,刚看了两组音视频文件时间是一样的
![image](https://github.com/user-attachments/assets/3622ba28-5769-4d01-82c7-c6e8d50cb6e9)

**Comment by mzky** [comment]
你太牛了 差异这么小都能发现，我再研究研究
![image](https://github.com/user-attachments/assets/9e872c57-a84e-4ac5-a69d-5753f1f67989)
![image](https://github.com/user-attachments/assets/6a0d302a-d3ac-4479-8765-c2e27276e144)

**Comment by datou1996** [comment]
剪视频的时候发现的，总感觉口型和声音对不上

**Comment by mzky** [comment]
我估计是帧率问题，有些视频29.97 FPS转到30 FPS后，少了几百毫米 
我加了个自动音视频同步参数，外加两个可以输入的偏移量参数，你再试试，麻烦反馈一下验证结果
偏移参数均为向右偏移
![image](https://github.com/user-attachments/assets/1b242e91-8d33-46a8-9df4-5202be04d8a6)

```
Options:
  --assOFF, -g
        是否关闭自动生成ass弹幕，默认不关闭
  --cachePath, -c string
        自定义缓存路径，默认使用BiliBili的默认路径 (default C:\Users\mzky\Videos\bilibili)
  --ffMpeg, -f string
        自定义FFMpeg文件路径
  --help, -h
        帮助信息
  --offsetAudio, -a string
        自定义音频偏移量
  --offsetVideo, -v string
        自定义视频偏移量
  --overlay, -o
        是否覆盖已存在的视频，默认不覆盖
```

https://github.com/mzky/m4s-converter/releases/download/test/m4s-converter.exe

**Comment by mzky** [comment]
好的 我再研究研究

**Comment by mzky** [comment]
我用的精简版ffmpeg不支持偏移量修改，我再想想办法

**Comment by mzky** [comment]
用ffmpeg始终达不到理想的效果，今天分析了bilibili的音视频文件，发现他们是用开源的GPAC工具处理音视频的，我增加了一个-g参数，用GPAC工具进行合成试试
新版工具下载：https://github.com/mzky/m4s-converter/releases/download/test/m4s-converter-base.exe
GPAC工具下载：https://gpac.io/downloads/gpac-nightly-builds/
![image](https://github.com/user-attachments/assets/06c62461-fe78-4efb-a3e1-33f56eef51fd)
执行.\m4s-converter-386.exe -g
选这个
![image](https://github.com/user-attachments/assets/33794bbe-3d2a-467a-bb44-5e2e1e2e3581)

**Comment by datou1996** [comment]
可以同步了，十分感谢

**Comment by mzky** [comment]
> 可以同步了，十分感谢，还有一个小问题，我是否可以指定默认的mp4box路径，类似于.\m4s-converter.exe -g ＂C:\xxx\xxx\mp4box.exe＂的命令来跳过多次选择文件的步骤。
修改了 -g 参数，可以直接写路径：./m4s-converter-amd64 -g "C:\Program Files (x86)\GPAC\mp4box.exe" 
也可以使用select参数弹出选择窗口 ./m4s-converter-amd64 -g select

https://github.com/mzky/m4s-converter/releases/tag/v1.4.0

**Comment by mzky** [comment]
新版默认使用内置的MP4Box，不需要自定义路径了
