### ISSUE TITLE
选择其他缓存路径后直接显示回车退出

### ISSUE THREAD

**Issue by RyeCa** [mzky/m4s-converter#12]
![image](https://github.com/user-attachments/assets/44465e76-c930-4626-9669-e0fa45e5b1a5)
![image](https://github.com/user-attachments/assets/bf48be1b-3371-4147-be98-08bc881a13dd)
![image](https://github.com/user-attachments/assets/1de550eb-7cb1-45f4-85b1-05f7aceec400)
麻烦开发者老哥看下是啥问题(*^_^*)

**Comment by mzky** [comment]
看下目录下有load_log文件吗，或者用的版本是最新的么？

**Comment by RyeCa** [comment]
又重新下载试了一下，是最新的 1.3.9 版本，日志如下

**Comment by RyeCa** [comment]
2024-11-12_14:56:16 [INFO ] 第一次运行,自动释放ffmpeg
2024-11-12_14:56:17 [WARN ] BiliBili缓存路径 C:\Users\12551\Videos\bilibili未找到缓存文件,
请重新选择 BiliBili 缓存文件路径！
2024-11-12_14:56:23 [INFO ] 选择的 BiliBili 缓存目录为:D:\bili_download
2024-11-12_14:56:23 [INFO ] 查找缓存目录下可转换的文件...
2024-11-12_14:57:02 [WARN ] BiliBili缓存路径 C:\Users\12551\Videos\bilibili未找到缓存文件,
请重新选择 BiliBili 缓存文件路径！
2024-11-12_14:57:06 [INFO ] 选择的 BiliBili 缓存目录为:D:\bili_download
2024-11-12_14:57:06 [INFO ] 查找缓存目录下可转换的文件...

**Comment by mzky** [comment]
看下缓存目录里有没有m4s后缀的文件，看日志是没找到能转换的文件

**Comment by mzky** [comment]
![image](https://github.com/user-attachments/assets/18efa68f-5284-4b65-bff4-ed778815d164)
里面是这样的么

**Comment by RyeCa** [comment]
![image](https://github.com/user-attachments/assets/0c19b469-bcd9-436d-bc2b-9d054726bc7d)
目录里是有 m4s 文件的

**Comment by RyeCa** [comment]
https://www.bilibili.com/bangumi/play/ss25582

**Comment by RyeCa** [comment]
缓存的内容是这个：https://www.bilibili.com/bangumi/play/ss25582

**Comment by mzky** [comment]
好的 我试试

**Comment by mzky** [comment]
修改了一下遍历缓存目录下的文件，试一下这个版本：https://github.com/mzky/m4s-converter/releases/download/test/m4s-converter-base.exe

**Comment by RyeCa** [comment]
> 修改了一下遍历缓存目录下的文件，试一下这个版本：https://github.com/mzky/m4s-converter/releases/download/test/m4s-converter-base.exe

试了一下，在win11里，选择缓存目录的时候无法选中文件夹
![image](https://github.com/user-attachments/assets/ffc04cb4-46bb-4aeb-afc2-a0540e82d205)

**Comment by mzky** [comment]
更新了一下查找m4s文件的函数，我本地试了没问题了：https://github.com/mzky/m4s-converter/releases/download/test/m4s-converter-386.exe

**Comment by RyeCa** [comment]
> 重构了查找m4s文件的函数，我本地试了没问题了： https://github.com/mzky/m4s-converter/releases/tag/v1.4.0

老哥我试了一下好像还是不行，和之前是一样的

**Comment by mzky** [comment]
好奇怪 我把试了好几次 是把数字目录 放到别的磁盘 没发现有问题，我这也是win11，你试试右键管理员权限执行看看
![image](https://github.com/user-attachments/assets/81f72d5f-d8ac-4365-b579-e689e7049bd0)
![image](https://github.com/user-attachments/assets/6d9082b1-b538-4b54-a31c-a4765dff2e9a)

**Comment by mzky** [comment]
是追番那个标签？
你给的地址 我这打不开
![image](https://github.com/user-attachments/assets/ee6c563f-37d9-4d92-8293-47fbdd072c4d)

**Comment by RyeCa** [comment]
试一下其他番剧，我试了下其他能缓存的动画都会出现这个问题

**Comment by RyeCa** [comment]
https://www.bilibili.com/bangumi/play/ep543143 可以试一下这个，我试了这个能在大陆以外的地区缓存

**Comment by mzky** [comment]
好的 我研究研究

**Comment by mzky** [comment]
找到问题了，番剧的json和普通视频的json格式不一样（吐槽一下，这两块肯定不是同一个团队做的，竟然不一致），已兼容
https://github.com/mzky/m4s-converter/releases/tag/v1.4.1

**Comment by RyeCa** [comment]
感谢开发者老哥，试了一下已经可以正常使用了😁👍，可以给个二维码给你赞助一下

**Comment by mzky** [comment]
这个程序之前一直是自己用的，看到知乎上有人需要就发上来了，没准备靠这个赚钱，谢谢支持！
