### ISSUE TITLE
历史合并过的文件自动跳过

### ISSUE THREAD

**Issue by GGbond233** [mzky/m4s-converter#13]
能否加入历史合并过的视频，就只合并新下载的功能哇

**Comment by mzky** [comment]
之前有位用户提过一个问题，有些视频组的名字和视频名称都相同，但不是同一个视频的问题，如图：
![image](https://github.com/user-attachments/assets/e6bf2b02-316d-4032-ab8f-c90252899b89)
后面我再研究研究，看看确定确实是同一个文件的时候跳过

**Comment by mzky** [comment]
已更新，增加了一个 -s 参数，用来跳过重名文件：https://github.com/mzky/m4s-converter/releases/tag/v1.5.1
