### ISSUE TITLE
请教一下steam录制视频的导出

### ISSUE THREAD

**Issue by bweq8527** [mzky/m4s-converter#14]
大佬你好，我最近遇到了一个问题：由于steam录制之后还需要手动导出mp4格式文件，所以这个时候不能同时玩游戏，如果想要在玩游戏的同时对录制的视频进行导出，就需要另一台电脑。所以我想在**mac平台**中导出**win平台steam录制的录像文件**，我是通过smb协议把win端存放录制文件的硬盘直接共享给mac，虽然mac可以预览剪辑文件，但是导出时mac端steam提醒我“无法获取剪辑信息”。

请问大佬对steam视频导出的流程有没有了解，我查看了一下steam录制的文件夹，当中有很多.m4s格式的小片段，以及一些json文件，初步猜测是没有加密手段。我想请教一下通过这些文件来导出mp4格式的视频可不可行？

非常感谢！

**Comment by mzky** [comment]
我没用过steam,能否找个小文件发我小看看



---- 回复的原邮件 ----
| 发件人 | Tianyao ***@***.***> |
| 日期 | 2024年12月30日 18:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [mzky/m4s-converter] 请教一下steam录制视频的导出 (Issue #14) |

大佬你好，我最近遇到了一个问题：由于steam录制之后还需要手动导出mp4格式文件，所以这个时候不能同时玩游戏，如果想要在玩游戏的同时对录制的视频进行导出，就需要另一台电脑。所以我想在mac平台中导出win平台steam录制的录像文件，我是通过smb协议把win端存放录制文件的硬盘直接共享给mac，虽然mac可以预览剪辑文件，但是导出时mac端steam提醒我“无法获取剪辑信息”。

请问大佬对steam视频导出的流程有没有了解，我查看了一下steam录制的文件夹，当中有很多.m4s格式的小片段，以及一些json文件，初步猜测是没有加密手段。我想请教一下通过这些文件来导出mp4格式的视频可不可行？

非常感谢！

**Comment by bweq8527** [comment]
好的，这是我之前录的一小段，大佬你看看，多谢啦
[clip_2767030_20241225_140805.zip](https://github.com/user-attachments/files/18275370/clip_2767030_20241225_140805.zip)

**Comment by mzky** [comment]
> 好的，这是我之前录的一小段，大佬你看看，多谢啦 [clip_2767030_20241225_140805.zip](https://github.com/user-attachments/files/18275370/clip_2767030_20241225_140805.zip)

刚试了一下，你录制这个m4s是在线播放的流方式，理论上用FFMpeg是可以转换的，但缺m3u8文件，不过这个跟bilibili的逻辑完全不一样，我这个工具帮不到你

**Comment by mzky** [comment]
另外我也试了其他两个转换工具，都是报错的，我不确定是不是你发送的文件问题
![image](https://github.com/user-attachments/assets/67679a61-74d5-47cf-a3d8-72ace246fdb5)

**Comment by bweq8527** [comment]
😭这样啊，好吧，麻烦大佬了。

**Comment by bweq8527** [comment]
请问大佬说的m3u8文件是干什么用的，我在录制文件夹下没有找到m3u8格式的文件

**Comment by mzky** [comment]
https://m.bilibili.com/opus/976202756005036035



---- 回复的原邮件 ----
| 发件人 | Tianyao ***@***.***> |
| 日期 | 2024年12月31日 11:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mzky/m4s-converter] 请教一下steam录制视频的导出 (Issue #14) |

请问大佬说的m3u8文件是干什么用的，我在录制文件夹下没有找到m3u8格式的文件

**Comment by bweq8527** [comment]
了解了，感谢大佬
