### ISSUE TITLE
还是不会用，能否稍微指点下

### ISSUE THREAD

**Issue by getsources** [mzky/m4s-converter#2]
百度没找到好工具，结果这里有。
是这样放在目标文件夹运行还是怎么用
![屏幕截图 2024-03-06 214139](https://github.com/mzky/m4s-converter/assets/35262603/c35346f8-34bd-4a3b-83a6-144ca21a014c)

**Comment by getsources** [comment]
有截图

**Comment by mzky** [comment]
已更新：https://github.com/mzky/m4s-converter/releases/tag/v1.3.0
![image](https://github.com/mzky/m4s-converter/assets/13345233/eb642845-ad2a-4ddb-a88f-d389309b1095)
![image](https://github.com/mzky/m4s-converter/assets/13345233/3b339a7c-a91e-4036-a95f-a0e958d268bf)

**Comment by getsources** [comment]
> 已更新：https://github.com/mzky/m4s-converter/releases/tag/v1.3.0
> ![image](https://github.com/mzky/m4s-converter/assets/13345233/eb642845-ad2a-4ddb-a88f-d389309b1095)
> ![image](https://github.com/mzky/m4s-converter/assets/13345233/3b339a7c-a91e-4036-a95f-a0e958d268bf)
> 

![Screenshot_2023-10-25-17-38-33-108_com.ss.android.ugc.aweme-edit.jpg](https://github.com/mzky/m4s-converter/assets/35262603/ef1acc03-cc08-404c-a9b3-549413959af0)

神速
