### ISSUE TITLE
videoinfo.json

### ISSUE THREAD

**Issue by Misaki-Wang** [mzky/m4s-converter#3]
现在B站改为json格式了，原来合并用的`.videoinfo`改为了`videoinfo.json`，可以考虑更改下

**Comment by mzky** [comment]
感谢反馈，刚看了一下最新版本两个文件都有，估计后续会吧`.videoinfo`去掉，一会我加一下两个文件都支持
![image](https://github.com/mzky/m4s-converter/assets/13345233/18b0c843-582d-4bf8-a37e-843bd92e520d)

**Comment by mzky** [comment]
已增加支持：https://github.com/mzky/m4s-converter/releases/tag/v1.3.1
