### ISSUE TITLE
feat: 跨平台支持

### ISSUE THREAD

**Issue by Hypoths** [mzky/m4s-converter#7]
Bilibili客户端现在已跨平台，并且似乎使用了相同的加密逻辑。但此程序目前似乎无法在`Linux`平台上顺利构建，希望能够进行跨平台支持。

**Comment by mzky** [comment]
这个我倒是没想过 还有用linux看bilibili的？

**Comment by mzky** [comment]
等我抽空改一下，准备用tag方式  
1、集成linux版ffmpeg
2、弹窗可以使用跨平台弹窗库，或者控制台输出
```
go build -ldflags "-w -s" -tags 'linux'
go build -ldflags "-w -s" -tags 'windows'
```
