### ISSUE TITLE
请问是否支持手机版缓存下来的文件(目录结构)?

### ISSUE THREAD

**Issue by i1itione** [mzky/m4s-converter#9]
例如像这样的目录结构：
D:\Phone\download\1405986388\c_1598174399\112
在 112 文件夹里存有 audio.m4s、video.m4s 和 index.json

前述 "download" 这个文件夹是从手机上提取的，路径如下：
/Android/data/tv.danmaku.bili/download

**Comment by mzky** [comment]
刚试了一下，手机上的目录结构和xml文件都不太一样，我研究研究先

**Comment by mzky** [comment]
已更新：https://github.com/mzky/m4s-converter/releases/tag/v1.3.9
操作步骤：
1、假设手机的bilibili已经缓存文件在`/Android/data/tv.danmaku.bili/download/1405986388/c_1598174399`中，不需要关c_开头的文件夹，拷贝上层的1405986388到PC中即可
2、建议将手机`/Android/data/tv.danmaku.bili/download`下的所有文件夹全部拷贝到`C:\Users\自己用户名\Videos\bilibili\`下
3、运行转换工具

**Comment by mzky** [comment]
> 已更新：https://github.com/mzky/m4s-converter/releases/tag/v1.3.9 操作步骤： 1、假设手机的bilibili已经缓存文件在`/Android/data/tv.danmaku.bili/download/1405986388/c_1598174399`中，不需要管`c_`开头的文件夹，拷贝上层的1405986388到PC端即可 2、建议将手机`/Android/data/tv.danmaku.bili/download`下的所有文件夹全部拷贝到`C:\Users\自己用户名\Videos\bilibili\`下 3、运行转换工具

手机`/Android/data/tv.danmaku.bili/download`下的所有文件夹都需要拷贝到`C:\Users\自己用户名\Videos\bilibili\`下，否则会报错，类似：
[WARN ] 找不到.playurl文件:
C:\BILI\567919165\c_1040074009\32\.playurl
[ERROR] 跳过未缓存完成的视频
[ERROR] 创建目标文件失败: open : The system cannot find the file specified.

**Comment by mzky** [comment]
目录结构：
```
C:.
└─bilibili缓存路径
  │  load_log
  │
  ├─350921235 (PC端结构)
  │      .playurl
  │      .videoInfo
  │      350921235_p1-1-30080.m4s
  │      350921235_p1-1-30280.m4s
  │      dm1
  │      group.jpg
  │      image.jpg
  │      videoInfo.json
  │      view
  │
  ├─712021944  (从Android手机中复制过来的目录)
  │  └─c_235489817
  │      │  danmaku.ass
  │      │  danmaku.xml
  │      │  entry.json
  │      │
  │      └─80
  │              audio.m4s
  │              index.json
  │              video.m4s
  │
  └─output
```

**Comment by HorseMoro** [comment]
你好，安卓手机下载哪一个？

**Comment by mzky** [comment]
> 你好，安卓手机下载哪一个？

不是在手机端安装,是从手机端下载文件到PC,用PC工具合成
